name: googleiolapaz
description: Presentation project for Google IO developed in peace. Theme Doing things with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: 4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Jetbrainsmono
      fonts:
        - asset: assets/fonts/jetbrainsmono/JetBrainsMono-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/jetbrainsmono/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/jetbrainsmono/JetBrainsMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/jetbrainsmono/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/jetbrainsmono/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/jetbrainsmono/JetBrainsMono-Light.ttf
          weight: 300
        - asset: assets/fonts/jetbrainsmono/JetBrainsMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/jetbrainsmono/JetBrainsMono-Thin.ttf
          weight: 100